#!/usr/bin/bash
# [ -s /usr/bin/frawk ] && alias awk="frawk"
[ -s /usr/bin/grep ] && alias grep=rg
DATA_DIR=$HOME/.local/bin/nix-db/db
RAM_DIR=/tmp
RAM_DATA=$RAM_DIR/db/data
WHERE_DIR=$RAM_DATA
toRam(){ /bin/cp -rf "$DATA_DIR" $RAM_DIR > /dev/null;}
toRam
getFiles(){ files=($(find "$WHERE_DIR" -type f -name '*.tsv'));}
getFiles
getVars(){
	for var in $(head -n1 "$file"); do
		vars+=("$var")
	done;}
whereVar(){
	vars=($(head -n1 "$file"))
	for var in "${vars[@]}"; do
		[ "$var" = "$1" ] && echo "${!vars[@]}" && return
	done;}
where(){ awk -v where="$(whereVar "$1")" -v which="$2" '$where ~ which';}
wh(){ where "$@" | tee;}
whereDate(){ where date "$1";}
whereItem(){ where item "$1";}
whereCost(){ where cost "$1";}

whereEx(){ awk -v where="$(whereVar "$1")" -v which="$2" '$where == which';}
wex(){ whereEx "$@";}

get(){ awk -v which="$(whereVar "$1")" 'NF {print $which}';}
gt(){ awk -v which="$(whereVar "$1")" 'NF {print $which}' "$2";}
getAll(){ awk 'NF {print}' "${files[@]}";}
getDate(){ get date;}
getItem(){ get item;}
getCost(){ get cost;}
getItemNum(){ get item | cut -d'_' -f1;}
getItemNumOnly(){ getItem | cut -d'-' -f1;}

sum(){ tr -d ',' | awk '{sum += $0} END {print sum}';}
sumh(){ printf "%'.3f\n" "$(sum)";}

whereClean(){ where "$@";}

day(){ cut -d'-' -f1;}
mon(){ cut -d'-' -f2;}
yr(){ cut -d'-' -f3;}

alias ga=getAll
alias gat="getAll | column -t"
alias wcl=whereClean
